/**
 * Every endpoint the frontend is allowed to call, in one place. Paths are
 * relative to the same-origin `/gateway` proxy (see next.config.ts
 * rewrites), which forwards to the real Gateway deployment. Keys match
 * the corresponding *.service.ts file names 1:1.
 */
export const endpoints = {
  auth: {
    signup: "/auth/signup",
    login: "/auth/login",
    session: "/auth/session",
    logout: "/auth/logout",
  },
  health: "/health",
  countries: "/countries",
  dashboard: "/dashboard",
  blueprint: "/blueprint",
  blueprintVersions: "/blueprint/versions",
  blueprintRestore: "/blueprint/restore",
  blueprintCompare: "/blueprint/compare",
  company: "/companies",
  workflow: "/workflows",
  provider: "/providers",
  providerTest: "/providers/test",
  providerDisconnect: "/providers/disconnect",
  integration: "/integrations",
  integrationTest: "/integrations/test",
  integrationDisconnect: "/integrations/disconnect",
  mapping: "/mappings",
  mappingPreview: "/mappings/preview",
  mappingDelete: "/mappings/delete",
  schema: "/schema",
  schemaDelete: "/schema/delete",
  schemaValidate: "/schema/validate",
  schemaVersions: "/schema/versions",
  companyApiKey: "/company/api-key",
  companyRotateSecret: "/company/rotate-secret",
  companyTestEndpoint: "/company/test-endpoint",
  sdk: (language: string) => `/sdk/${language}`,
  security: "/security",
  analytics: "/analytics",
  graph: "/graph",
  replay: "/replay",
  ai: "/ai",
  intelligence: {
    dashboard: "/intelligence/dashboard",
    reports: "/intelligence/reports",
    notifications: "/intelligence/notifications",
    forecast: "/intelligence/forecast",
    performance: "/intelligence/performance",
    knowledge: "/intelligence/knowledge",
    history: "/intelligence/history",
    status: "/intelligence/status",
    preferences: "/intelligence/preferences",
  },
  marketplace: "/marketplace",
  enterprise: "/enterprise",
  developer: "/developer",
} as const;
